### PR TITLE
Language clarification

### PR DESCRIPTION
**Pull request by ronancremin**
Clarify language around entities & passive fingerprinting

***
<a href="https://pr-preview.s3.amazonaws.com/ronancremin/ua-client-hints/pull/239.html" title="Last updated on May 31, 2021, 12:38 PM UTC (6479f38)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/ua-client-hints/239/017499a...ronancremin:6479f38.html" title="Last updated on May 31, 2021, 12:38 PM UTC (6479f38)">Diff</a>

### CODE REVIEW

**Comment by yoavweiss** [comment]
Hey @ronancremin!

I'll let @miketaylr weigh in, but IMO, "the network" and "the server" are not interchangeable here. The former also explains why e.g. this feature is limited to secure contexts, while the latter does not.

**Comment by ronancremin** [comment]
We discussed this in #236. The phrase "available to the network" doesn't feel right given that UA-CH will only be sent in secure contexts where network elements other than the destination server should not be able to see request payloads in any case.

**Comment by amtunlimited** [comment]
> UA-CH will only be sent in secure contexts

No real opinion on the wording here, but I think the " default entropy available" referred to by 

> reduce the default entropy available to the network for [=passive fingerprinting=]

Is referring to the current status of the `User-Agent` request header, which is available on all requests

**Comment by ronancremin** [comment]
Agreed, but in a HTTPS world the entropy is not available to _network_, it's only available to the destination server.

**Comment by miketaylr** [comment]
> but IMO, "the network" and "the server" are not interchangeable here. The former also explains why e.g. this feature is limited to secure contexts, while the latter does not.

@yoavweiss can you elaborate? I'm not sure I follow.

> Agreed, but in a HTTPS world the entropy is not available to the _network_, it's only available to the destination server.

There may be more than one destination server though, right? (In the case of a a page with 3rd party subresources... but by default they won't get certain hints unless delegated to).

That said, I'm not sure the difference between network and server is super meaningful, but I'm curious to hear more from @yoavweiss before landing this.

**Comment by yoavweiss** [comment]
Ignore me, I just realized that there's a full section above talking about network based attacks, and why we're limiting the feature to secure contexts above the one that's modified. I'm fine with this change.

**Comment by miketaylr** [comment]
No worries, thanks for taking a look!

**Review by miketaylr — APPROVED** [review]
LGTM, thanks @ronancremin

**Pull request merged**
