### PR TITLE
Fixes #186 - Add Sec-CH prefix to UA-CH tokens

### LINKED ISSUE #186: Update tokens to be consistent with Client Hints I-D
This landed in Chromium today(ish): https://bugs.chromium.org/p/chromium/issues/detail?id=1153688

### PR DESCRIPTION
**Pull request by miketaylr**
PTAL @amtunlimited

***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/ua-client-hints/pull/187.html" title="Last updated on Jan 22, 2021, 6:36 PM UTC (35c612f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/ua-client-hints/187/1e6cc1c...miketaylr:35c612f.html" title="Last updated on Jan 22, 2021, 6:36 PM UTC (35c612f)">Diff</a>

### CODE REVIEW

**Review by amtunlimited — CHANGES_REQUESTED** [review]
Can you fix the explainer as well?

**Comment by miketaylr** [comment]
Oh, right. Forgot about that. 🙈

**Review by amtunlimited — APPROVED** [review]
LGTM

**Comment by miketaylr** [comment]
thanks!

**Comment by miketaylr** [comment]
The other half to this is https://github.com/WICG/client-hints-infrastructure/pull/47/files, but I think we can merge this in first.

**Pull request merged**
