### PR TITLE
Fixes #213 - Make platform a default, low-entropy hint

### LINKED ISSUE #213: Make platform a low-entropy hint
It's already possible to infer platform (OS) through various web platform APIs, without looking at the `User-Agent` header or `navigator.userAgent`, so I think we should move "platform" from high entropy to low. Platform version should remain high entropy. 

Some examples:

* canPlayType + HLS MIME can be used to detect Android (for Chrome & Firefox), or macOS (Safari, pre-Chromium Edge)
* Blob.size can be used to detect native CRLF (Windows) vs LF (Mac / Linux) line endings
* Detecting scrollbar width to infer OS (via innerWidth & clientWidth)
* Detecting OS specific and available fonts (-apple-system, BlinkMacSystemFont, Segoe UI, etc.)
* Canvas / WebGL fingerprinting techniques (Notably Picasso, among other research, etc.) 
* navigator.platform, navigator.appVersion, navigator.oscpu (Gecko-only)

In terms of what this would mean, we would stick `Sec-CH-UA-Platform` into the low-entropy table, and update relevant bits here: https://wicg.github.io/ua-client-hints/#interface

### PR DESCRIPTION
**Pull request by miketaylr**
(I did some alphabetizing of the header sections, so reviewing commit by commit might be less messy - the normative changes are all in d15da06)

PTAL @amtunlimited @yoavweiss 

(this still needs a PR against infra before merging)

***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/ua-client-hints/pull/221.html" title="Last updated on Apr 1, 2021, 6:03 PM UTC (d15da06)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/ua-client-hints/221/c8719a3...miketaylr:d15da06.html" title="Last updated on Apr 1, 2021, 6:03 PM UTC (d15da06)">Diff</a>

### CODE REVIEW

**Comment by jridgewell** [comment]
Cross linking: This is a breaking change, and depends on some resolution to https://github.com/WICG/ua-client-hints/issues/222.

**Comment by miketaylr** [comment]
> This is a breaking change

For browsers that have already implemented UA-CH yeah (e.g., Chromium), but for new browsers, not really.

> depends on some resolution to #222.

Yeah, let's discuss there.

**Review by yoavweiss — APPROVED** [review]
LGTM

**Comment by yoavweiss** [comment]
Would it make sense to integrate some of the reasoning you outlined in the doc for exposing this as a low entropy hint in the explainer here or in the ch-infra repo? It seems to largely apply to the other hints exposed by default

**Comment by miketaylr** [comment]
> Would it make sense to integrate some of the reasoning you outlined in the doc for exposing this as a low entropy hint in the explainer here or in the ch-infra repo? It seems to largely apply to the other hints exposed by default

Yeah, I think a section for "high vs low entropy and how it relates to default hints" would be useful in general. I'll file a follow-up and aim to write something in the coming weeks.

**Pull request merged**
